### ISSUE TITLE
Panic when trying to add package to new project

### ISSUE THREAD

**Issue by demizer** [nektro/zigmod#61]
Thanks for creating this infrastructure! It's really nice!

zigmod version: zigmod dev linux x86_64 gnu (git latest)
zig version: 0.10.0-dev.1107+7deadf430

```
$ zigmod aq add 1/jecolon/zigstr
thread 1263450 panic: attempt to use null value
/mnt/data/src/zig/zigmod/src/cmd/aquila/add.zig:24:52: 0x609ca8 in .zigmod.cmd.aquila.add.do (zigmod)
        val.getT(.{ "pkg", "RemoteName" }, .String).?,
                                                   ^
/mnt/data/src/zig/zigmod/src/cmd/aquila/add.zig:14:15: 0x607c42 in .zigmod.cmd.aquila.add.execute (zigmod)
    _ = try do(std.fs.cwd(), pkg_id);
              ^
/mnt/data/src/zig/zigmod/src/cmd/aq.zig:38:28: 0x5706bc in .zigmod.cmd.aq.execute (zigmod)
            try cmd.execute(args[1..]);
                           ^
/mnt/data/src/zig/zigmod/src/main.zig:53:28: 0x56b314 in main (zigmod)
            try cmd.execute(args[1..]);
                           ^
/home/demizer/zig-linux-x86_64-0.10.0-dev.1107+7deadf430/lib/std/start.zig:561:37: 0x6a1467 in std.start.callMain (zigmod)
            const result = root.main() catch |err| {
                                    ^
fish: Job 1, 'zigmod aq add 1/jecolon/zigstr' terminated by signal SIGABRT (Abort)
```

coredump backtrace:

```
(gdb) bt full
#0  0x00007f95d1c50d22 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007f95d1c3a862 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x0000000000572149 in std.os.abort () at /home/demizer/zig-linux-x86_64-0.10.0-dev.1107+7deadf430/lib/std/os.zig:448
No locals.
#3  0x000000000056a21b in std.debug.panicImpl (trace=0x0, first_trace_addr=..., msg=...) at /home/demizer/zig-linux-x86_64-0.10.0-dev.1107+7deadf430/lib/std/debug.zig:338
No locals.
#4  0x0000000000567748 in std.builtin.default_panic (msg=<error reading variable: Cannot access memory at address 0x0>, error_return_trace=0x0)
    at /home/demizer/zig-linux-x86_64-0.10.0-dev.1107+7deadf430/lib/std/builtin.zig:820
        first_trace_addr = 6331561
#5  0x0000000000609ca9 in .zigmod.cmd.aquila.add.do (dir=..., pkg_id=...) at /mnt/data/src/zig/zigmod/src/cmd/aquila/add.zig:24
        url = {ptr = 0xa6d3c0 "https://aquila.red/1/jecolon/zigstr", len = 35}
        pkg_url = {ptr = 0x4 <error: Cannot access memory at address 0x4>, len = 4}
        m = {id = {ptr = 0x50573faf10b88100 <error: Cannot access memory at address 0x50573faf10b88100>, len = 140722658384064}, name = {
            ptr = 0xffffffffffffff60 <error: Cannot access memory at address 0xffffffffffffff60>, len = 0}, main = {
            ptr = 0x551040 <_start> "1\355I\211\321^H\211\342H\203\344\360PTL\215\005\252\064\"", len = 0}, c_include_dirs = {ptr = 0x0, len = 0}, c_source_flags = {
            ptr = 0x7f95d1c9f9e8 <free+104>, len = 140722658384736}, c_source_files = {ptr = 0xa6d350, len = 140722658384160}, deps = {ptr = 0x774470 <__libc_csu_init>, len = 140722658383904},
          yaml = {items = {ptr = 0x572c05 <std.heap.CAllocator.alignedFree+21>, len = 10933008}}, root_files = {ptr = 0xa6d310, len = 140722658383952}, files = {
            ptr = 0x567aa1 <std.heap.CAllocator.free+33>, len = 140722658384072}, rootdeps = {ptr = 0x572e0d <std.array_list.ArrayListAligned(u8,null).deinit+61>, len = 4300651113}, builddeps = {
            ptr = 0x0, len = 140722658384160}, min_zig_version = <error reading variable>
        d = {alloc = {ptr = 0x551040 <_start>, vtable = 0x7f95d1ca0f26 <posix_memalign+54>}, type = 112, path = {
            ptr = 0x5729b4 <std.heap.CAllocator.alignedAlloc+164> "\203", <incomplete sequence \370>, len = 4096}, id = {ptr = 0xa6d350 "\220Ӧ", len = 10933072}, name = {ptr = 0x0,
            len = 140722658383648}, main = {ptr = 0x8 <error: Cannot access memory at address 0x8>, len = 95}, version = {ptr = 0x8 <error: Cannot access memory at address 0x8>, len = 8},
          c_include_dirs = {ptr = 0xa6d350, len = 10933072}, c_source_flags = {ptr = 0x4d430001, len = 140722658383648}, c_source_files = {ptr = 0x8, len = 0}, only_os = {ptr = 0x0, len = 0},
          except_os = {ptr = 0x50573faf10b88100, len = 140722658383856}, yaml = <error reading variable>
        d = {alloc = {ptr = 0x7ffc8c10a030, vtable = 0x7ffc8c109850}, type = 80, path = {ptr = 0x100000400000003 <error: Cannot access memory at address 0x100000400000003>, len = 44}, id = {
            ptr = 0x18 <error: Cannot access memory at address 0x18>, len = 140281446523838}, name = {
            ptr = 0x6b4a9b <std.array_list.ArrayListAligned(usize,null).ensureTotalCapacityPrecise+155> "f\203", <incomplete sequence \340>, len = 0}, main = {
            ptr = 0x5 <error: Cannot access memory at address 0x5>, len = 17179869185}, version = {ptr = 0x70 <error: Cannot access memory at address 0x70>, len = 95}, c_include_dirs = {
            ptr = 0x7, len = 44}, c_source_flags = {ptr = 0x58530b <std.array_list.ArrayListAligned(u8,null).ensureTotalCapacityPrecise+155>, len = 1}, c_source_files = {ptr = 0x3100000007,
            len = 0}, only_os = {ptr = 0x0, len = 0}, except_os = {ptr = 0x770000007c, len = 390842024046}, yaml = <error reading variable>
        err = (none)
        _anon = 5712901
        _anon = 140722658383088
        file = {handle = -1945069552, static default_mode = <optimized out>}
        val = {payload = {Object = {ptr = 0xa7f8f0, len = 10}, Array = {ptr = 0xa7f8f0, len = 10}, String = {ptr = 0xa7f8f0 "\262\252\247", len = 10}, Int = 11008240,
            Float = 5.4387932051754439e-317, Bool = false}, tag = Object}
#6  0x0000000000607c43 in .zigmod.cmd.aquila.add.execute (args=...) at /mnt/data/src/zig/zigmod/src/cmd/aquila/add.zig:14
        pkg_id = {ptr = 0xa6d39e "1/jecolon/zigstr", len = 16}
#7  0x00000000005706bd in .zigmod.cmd.aq.execute (args=...) at /mnt/data/src/zig/zigmod/src/cmd/aq.zig:38
No locals.
#8  0x000000000056b315 in main () at main.zig:53
        e = (none)
        _anon = 280375465148160
        sub_cmd_args = {items = {ptr = 0x0, len = 0}, capacity = 0, allocator = {ptr = 0x0, vtable = 0x0}}
        item = {ptr = 0x0, len = 0}
        result = {term = {payload = {Exited = 16 '\020', Signal = 7341584, Stopped = 7341584, Unknown = 7341584}, tag = Exited}, stdout = {ptr = 0x0, len = 6989697051418651002}, stderr = {
            ptr = 0x2f31006464610071 <error: Cannot access memory at address 0x2f31006464610071>, len = 71776119061217280}}
        proc_args = {ptr = 0xa6d350, len = 4}
--Type <RET> for more, q to quit, c to continue without paging--c
        args = {ptr = 0xa6d360, len = 3}
        gpa = <optimized out>
#9  0x00000000006a1468 in std.start.callMain () at /home/demizer/zig-linux-x86_64-0.10.0-dev.1107+7deadf430/lib/std/start.zig:561
        err = UnexpectedCharacter
#10 0x0000000000571f88 in std.start.initEventLoopAndCallMain () at /home/demizer/zig-linux-x86_64-0.10.0-dev.1107+7deadf430/lib/std/start.zig:495
No locals.
#11 std.start.callMainWithArgs (argc=4, argv=0x7ffc8c10a348, envp=...) at /home/demizer/zig-linux-x86_64-0.10.0-dev.1107+7deadf430/lib/std/start.zig:445
No locals.
#12 0x0000000000571d33 in std.start.main (c_argc=4, c_argv=0x7ffc8c10a348, c_envp=0x7ffc8c10a370) at /home/demizer/zig-linux-x86_64-0.10.0-dev.1107+7deadf430/lib/std/start.zig:460
        env_count = 55
        envp = {ptr = 0x7ffc8c10a370, len = 55}
```

**Comment by nektro** [comment]
fix for this will be released today

**Comment by nektro** [comment]
code fix in https://github.com/nektro/zigmod/commit/878428eddb7a5c0913d10e1673aa7ad05f981c63, release incoming

**Comment by nektro** [comment]
released in https://github.com/nektro/zigmod/releases/tag/r75
